= project-cpp-template


image:https://img.shields.io/github/workflow/status/qigao/project-cpp-template/Ubuntu/master?logoColor=grey&logo=ubuntu&label=[Linux Status,link="https://github.com/qigao/project-cpp-template/actions"]
image:https://img.shields.io/github/workflow/status/qigao/project-cpp-template/Windows/master?logoColor=grey&logo=windows&label=[Windows Status,link="https://github.com/qigao/project-cpp-template/actions"]
image:https://img.shields.io/github/workflow/status/qigao/project-cpp-template/MacOS/master?logoColor=grey&logo=apple&label=[macOS Status,link="https://github.com/qigao/project-cpp-template/actions"]
image:https://img.shields.io/github/license/qigao/project-cpp-template.svg?logoColor=silver&logo=open-source-initiative&label=&color=blue[MIT License,link="https://github.com/qigao/project-cpp-template/blob/master/LICENSE.txt"]
image:https://img.shields.io/github/v/tag/qigao/project-cpp-template.svg?logo=github&label=[Latest version,link="https://github.com/qigao/project-cpp-template/releases"]

This repository aims to represent a template for Modern C++ projects, including static analysis checks, autoformatting, a BDD/TDD capable test-suite and packaging

== Features

* `[x]` CMake and Conan based project template
* `[x]` qt6 widgets&qml style application demo
* `[x]` imgui-style application demo
* `[x]` plugin demo(shared/static)
* `[x]` BDD/TDD test-suite
* `[x]` GitHub actions with cache
* `[x]` Code coverage
* `[x]` Code formatting&linting
* `[x]` Basic CPack packaging

== Available CMake Options

* BUILD_TESTING - builds the tests (requires `doctest`)
* BUILD_SHARED_LIBS - enables or disables the generation of shared libraries
* BUILD_WITH_MT - valid only for MSVC, builds libraries as MultiThreaded DLL
* BUILD_WITH_QT6 - enables or disables the generation of qt6 widgets&qml style application demo
* CODE_COVERAGE - enables or disables the generation of code coverage
* USE_SANITIZER - enables or disables the generation of code coverage, could be Address,Leak,Memory,Thread,Undefined



== Add third party libs

update conanfile.txt from project root

== How to build from command line

The project can be built using the following commands:

[source,shell]
----
cd /path/to/this/project
cmake -S . -Bbuild -DBUILD_TESTING=TRUE -DBUILD_SHARED_LIBS=TRUE -G Ninja
cmake --build build --target format
cmake --build build --target package
----
