version: 3

includes:
  cpp_core_project:
    taskfile: ./core/Taskfile.yml
    optional: true
    dir: ./core
    vars:


vars:
  CMAKE_GENERATOR: "Ninja Multi-Config"
  CWD:
    sh: git rev-parse --show-toplevel

tasks:
  test:
    - task: myproj:test.all
    - task: myproj:test.release
    - task: install

  lint:
    deps:
      - task: cpp_core_project:lint::all
    cmds:
      - ~/vcpkg/vcpkg format-manifest ./vcpkg.json
      - npx -y cspell lint --no-progress --show-suggestions

  clean:
    cmds:
      - cmd: powershell -c 'function rmrf($path) { if (test-path $path) { rm -r -force $path }}; rmrf ./build; rmrf ./install'
        platforms: [windows]
      - cmd: rm -rf ./install ./build
        platforms: [linux, darwin]

  config:
    - cmake --preset=developer
