version: 3

includes:
  cpp_core_project: 
    taskfile: ./core/Taskfile.yml
    optional: true
    dir: ./core
    vars:
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs

vars:
  CMAKE_GENERATOR: "Ninja Multi-Config"
  CWD:
    sh: git rev-parse --show-toplevel

tasks:
  test:
    - task: myproj:test
    - task: myproj:test.release
    - task: install

  lint.cspell: npx -y cspell lint --no-progress --show-suggestions
  lint.vcpkg:
    cmds:
      - cmd: ~/vcpkg/vcpkg format-manifest ./vcpkg.json

  lint:
    deps:
      - lint.vcpkg
    cmds:
      - task: cpp_core_project:lint 

  clean:
    deps:
      - myproj:clean
      - install:clean
      - minimal:clean
    cmds:
      - cmd: powershell -c 'function rmrf($path) { if (test-path $path) { rm -r -force $path }}; rmrf ./install'
        platforms: [windows]
      - cmd: rm -rf ./install
        platforms: [linux, darwin]

  docs:
    deps:
      - docs:docs
  docs.preview:
    deps:
      - docs:docs.preview
  docs.deploy:
    deps:
      - docs:docs.deploy
      - docs:docs.deploy
  config:
    - cmake --preset=developer
      - docs:docs.deploy 
  config:
    - cmake --preset=developer
