server:
  port: 4443
  shared_folder: ./shared
  delete_after_download: true
  ssl:
    key_file: certs/example.com.key
    cert_file: certs/example.com.pem
  auth:
    enabled: true
    token: 123456
  webhook:
    url: http://localhost:4443/dump
    api_key: 123456
    headers:
      - header: x-test
        value: true
