# Notes
# - install task from: https://taskfile.dev/#/installation or use `setup-cpp --task true`
# - If using Visual Studio, either run the following commands inside the Visual Studio command prompt (vcvarsall) or set CMAKE_GENERATOR to "Visual Studio 17 2022"

version: 3
tasks:
  yaml_convert:test:
    cmds:
      - cmake --build  {{ .CMAKE_BUILD_DIR }}   --target yaml_convert_test
  yaml_convert:run:
    cmds:
      - bash -c {{ .CMAKE_BUILD_DIR }}/core/http_server/test/Debug/yaml_convert_test
  yaml_convert:coverage:
    deps:
      - yaml_convert:test
    cmds:
      - cmake --build   {{.CMAKE_BUILD_DIR}}  --target yaml_convert_coverage
  http_server:test:
    cmds:
      - cmake --build  {{ .CMAKE_BUILD_DIR }}   --target http_server_test
  http_server:run:
    cmds:
      - bash -c {{ .CMAKE_BUILD_DIR }}/core/http_server/test/Debug/http_server_test
  http_server:coverage:
    deps:
      - http_server:test
    cmds:
      - cmake --build   {{.CMAKE_BUILD_DIR}}  --target http_server_coverage
