version: 3
tasks:
  yaml_convert:test:
    cmds:
      - cmake --build  $BUILD_DIR  --target yaml_convert_test
  yaml_convert:run:
    deps:
      - task: yaml_convert:test
    cmds:
      - $OUTPUT_DIR/$BUILD_TYPE/yaml_convert_test
  yaml_properties:test:
    cmds:
      - cmake --build  $BUILD_DIR  --target yaml_properties_test
  yaml_properties:run:
    deps:
      - task: yaml_properties:test
    cmds:
      - $OUTPUT_DIR/$BUILD_TYPE/yaml_properties_test
  http_server:test:
    cmds:
      - cmake --build  $BUILD_DIR  --target http_server_test
  http_server:run:
    deps:
      - task: http_server:test
    cmds:
      - $OUTPUT_DIR/$BUILD_TYPE/http_server_test
