# Notes
# - install task from: https://taskfile.dev/#/installation or use `setup-cpp --task true`
# - If using Visual Studio, either run the following commands inside the Visual Studio command prompt (vcvarsall) or set CMAKE_GENERATOR to "Visual Studio 17 2022"

version: 3

tasks:
  test:
    cmds:
      - cmake --build --preset developer --target yaml_convert_test
  coverage:
    deps:
      - test
    cmds:
      - cmake --build --preset developer --target yaml_convert_coverage
