version: 3
tasks:
  yaml_convert.test.build:
    cmds:
      - cmd: $CMAKE_BUILD  test.http_server_lib.yaml_convert
  yaml_convert.test.run:
    deps:
      - task: yaml_convert.test.build
    cmds:
      - cmd: $CMAKE_TEST ^test\.http_server_lib\.yaml_convert$
  yaml_config.test.build:
    cmds:
      - cmd: $CMAKE_BUILD  test.http_server_lib.yaml_config
  yaml_config.test.run:
    deps:
      - task: yaml_config.test.build
    cmds:
      - cmd: $CMAKE_TEST ^test\.http_server_lib\.yaml_config$
  http_server.exe.build:
    cmds:
      - cmd: $CMAKE_BUILD  http_server

  http_server.test.build:
    cmds:
      - cmd: $CMAKE_BUILD test.http_server_lib.demo
  http_server.test.run:
    deps:
      - task: http_server.test.build
    cmds:
      - cmd: $CMAKE_TEST ^test\.http_server_lib\.demo$
