version: 3
tasks:
  func.test.build:
    cmds:
      - cmd: $CMAKE_BUILD test.my_lib.auto_function
  func.test.run:
    deps: [func.test.build]
    cmds:
      - cmd: $CMAKE_TEST ^test\.my_lib\.auto_function$
  singleton.test.build:
    cmds:
      - cmd: $CMAKE_BUILD test.my_lib.Singleton
  singleton.test.run:
    deps: [singleton.test.build]
    cmds:
      - cmd: $CMAKE_TEST ^test\.my_lib\.Singleton$
  human_read.test.build:
    cmds:
      - cmd: $CMAKE_BUILD test.my_lib.hr
  human_read.test.run:
    deps: [human_read.test.build]
    cmds:
      - cmd: $CMAKE_TEST ^test\.my_lib\.hr$
  hash.test.build:
    cmds:
      - cmd: $CMAKE_BUILD test.hashfunc.sha
  hash.test.run:
    deps: [hash.test.build]
    cmds:
      - cmd: $CMAKE_TEST ^test\.hashfunc\.sha$

  random.test.build:
    cmds:
      - cmd: $CMAKE_BUILD  test.my_lib.random
  random.test.run:
    deps: [random.test.build]
    cmds:
      - cmd: $CMAKE_TEST ^test\.my_lib\.random$
  my_lib.test.build:
    cmds:
      - cmd: $CMAKE_BUILD test.my_lib.my_sum
  my_lib.test.run:
    cmds:
      - cmd: $CMAKE_TEST ^test\.my_lib\.my_sum$
