# Notes
# - install task from: https://taskfile.dev/#/installation or use `setup-cpp --task true`
# - If using Visual Studio, either run the following commands inside the Visual Studio command prompt (vcvarsall) or set CMAKE_GENERATOR to "Visual Studio 17 2022"

version: 3
includes:
  server:
    taskfile: ./http_server/Taskfile.yml
  client:
    taskfile: ./http_client/Taskfile.yml
  shared:
    taskfile: ./shared/Taskfile.yml
 
