name: auto-clang-format
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        extensions: 'h,cpp,hpp'
        clangFormatVersion: 16
