name: ci
on:
  push:
    branches:
      - main
      - develop
      - master
    paths:
      - "core/**"
      - ".github/workflows/ci.yml"

  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "core/**"
      - ".github/workflows/ci.yml"
env:
  CMAKE_GENERATOR: "Ninja Multi-Config"
jobs:
  setup-build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{ matrix.os }}
    name: setup OS and compiler
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
          - windows-2022
        include:
          # Inject GCOV variable for gcc
          - compiler: gcc
            GCOV: gcov
          - os: windows-2022
            compiler: msvc
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/vcpkg
            ./build/vcpkg_installed
            ${{ env.CONAN_USER_HOME }}
            ~/.cache/pip
            ${{ env.HOME }}/.cache/vcpkg/archives
            ${{ env.XDG_CACHE_HOME }}/vcpkg/archives
            ${{ env.LOCALAPPDATA }}\vcpkg\archives
            ${{ env.APPDATA }}\vcpkg\archives
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('./vcpkg.json')}}-${{ matrix.CMAKE_GENERATOR }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('./vcpkg.json') }}-
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
          ninja: true
          vcpkg: true
          ccache: true
          clangtidy: true
          conan: 2.1.0
          task: true
          cppcheck: true
          gcovr: true
          opencppcoverage: true
      - name: install dependencies(Ubuntu)
        if: ${{  contains(matrix.os, 'ubuntu') || contains(matrix.os, 'debian') }}
        run: |
          sudo apt-get install -y  linux-libc-dev
      - name: Initialize CodeQL
        if: ${{ contains(matrix.os, 'ubuntu') && contains(matrix.compiler, 'llvm') }}
        uses: github/codeql-action/init@v3
        with:
          languages: "cpp"
      - name: config and setup project
        run: |
            task config
        env:
            CMAKE_GENERATOR: ${{env.CMAKE_GENERATOR}}
      - name: build all the project
        run: |
            task build.all
      - name: Test
        run: |
            task test.all
      - name: Test/Coverage
        run: |
            task coverage.all
      - name: Publish Tagged Release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/')  }}
        with:
            files: |
              build/*-*Release*-*.*
      - name: Publish to codecov
        uses: codecov/codecov-action@v4.0.1
        with:
            flags: ${{ runner.os }}
            name: ${{ runner.os }}-coverage
            files: ./build/coverage.xml
            token: ${{ secrets.CODECOV_TOKEN  }}
