name: MacOS
on:
  push:
    branches:
      - master
    paths:
      - "project/**"
      - "!project/examples/gui/**"
      - ".github/workflows/macos.yml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "project/**"
      - "!project/examples/gui/**"
      - ".github/workflows/macos.yml"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Python environment
        uses: actions/setup-python@v2
      - name: Install tools
        run: |
          brew install ninja
          brew install clang-format
      - name: Install conan
        run: |
          pip install conan --upgrade
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libc++ default
      - name: Configure cmake
        run: |
          cmake -S . -B build -DBUILD_TESTING=TRUE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build
        run: |
          cmake --build build --target install --config Release
