name: Ubuntu
on:
  push:
    branches:
      - master
    paths:
      - "project/**"
      - "!project/examples/gui/**"
      - ".github/workflows/ubuntu.yml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "project/**"
      - "!project/examples/gui/**"
      - ".github/workflows/ubuntu.yml"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Python environment
        uses: actions/setup-python@v2
      - name: Run Clang-Format
        run: python ./run-clang-format.py -r project
      - name: ubuntu install library
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build  libglfw3-dev libsdl2-dev gcc-multilib g++-multilib libfreetype6-dev libvulkan-dev
      - name: Install conan
        run: |
          pip install conan --upgrade
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Cmake Configure and Build
        run: |
          cmake -S . -B build -DBUILD_TESTING=TRUE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_BUILD_TYPE=Release -G Ninja
      - name: Build
        run: |
          cmake --build build --target install --config Release
