# Notes
# - install task from: https://taskfile.dev/#/installation or use `setup-cpp --task true`
# - If using Visual Studio, either run the following commands inside the Visual Studio command prompt (vcvarsall) or set CMAKE_GENERATOR to "Visual Studio 17 2022"

version: 3
tasks:
  http_client:test:build:
    cmds:
      - cmake --build  $BUILD_DIR   --target http_client_test
  http_client:test:run:
    deps:
      - task: http_client:test:build
    cmds:
      - cmd: cd $BUILD_DIR && ctest -R HttpClientTest
  sum:test:build:
    cmds:
      - cmake --build  $BUILD_DIR  --target sum_test
  sum:test:run:
    deps:
      - task: sum:test:build
    cmds:
      - cmd: cd $BUILD_DIR && ctest -R DemoTest
  yaml_convert:test:build:
    cmds:
      - cmake --build  $BUILD_DIR  --target client_yaml_convert_test
  yaml_convert:test:run:
    deps:
      - task: yaml_convert:test:build
    cmds:
      - cmd: cd $BUILD_DIR && ctest -R YAMLConverterTest
  yaml_properties:test:build:
    cmds:
      - cmake --build  $BUILD_DIR  --target client_yaml_test
  yaml_properties:test:run:
    deps:
      - task: yaml_properties:test:build
    cmds:
      - cmd:  cd $BUILD_DIR && ctest  -R RemoteYmlTest
