# Notes
# - install task from: https://taskfile.dev/#/installation or use `setup-cpp --task true`
# - If using Visual Studio, either run the following commands inside the Visual Studio command prompt (vcvarsall) or set CMAKE_GENERATOR to "Visual Studio 17 2022"

version: 3
tasks:
  http_client:test:build:
    cmds:
      - cmake --build  $BUILD_DIR   --target test.http_client.dll
  http_client:test:run:
    deps:
      - task: http_client:test:build
    cmds:
      - cmd: cd $BUILD_DIR &&  ctest -T test --build-config $BUILD_TYPE --stop-on-failure --no-tests=error -R ^test\.http_client\.dll$
  http_client:exe:build:
    cmds:
      - cmake --build  $BUILD_DIR  --target http_client
  sum:test:build:
    cmds:
      - cmake --build  $BUILD_DIR  --target test.http_client.sum
  sum:test:run:
    deps:
      - task: sum:test:build
    cmds:
      - cmd: cd $BUILD_DIR && ctest -T test  --build-config $BUILD_TYPE --stop-on-failure --no-tests=error -R ^test\.http_client\.sum$
  yaml_convert:test:build:
    cmds:
      - cmake --build  $BUILD_DIR  --target test.http_client.yaml_convert
  yaml_convert:test:run:
    deps:
      - task: yaml_convert:test:build
    cmds:
      - cmd: cd $BUILD_DIR &&  ctest -T test  --build-config $BUILD_TYPE --stop-on-failure --no-tests=error -R ^test\.http_client\.yaml_convert$
  yaml_config:test:build:
    cmds:
      - cmake --build  $BUILD_DIR  --target test.http_client.yaml_config
  yaml_config:test:run:
    deps:
      - task: yaml_config:test:build
    cmds:
      - cmd:  cd $BUILD_DIR &&  ctest -T test  --build-config $BUILD_TYPE --stop-on-failure --no-tests=error -R ^test\.http_client\.yaml_config$
