# Notes
# - install task from: https://taskfile.dev/#/installation or use `setup-cpp --task true`
# - If using Visual Studio, either run the following commands inside the Visual Studio command prompt (vcvarsall) or set CMAKE_GENERATOR to "Visual Studio 17 2022"

version: 3
tasks:
  http_client:test:
    cmds:
      - cmake --build  $BUILD_DIR   --target http_client_test
  http_client:run:
    deps:
      - task: http_client:test
    cmds:
      - $OUTPUT_DIR/$BUILD_TYPE/http_client_test
  sum:test:
    cmds:
      - cmake --build  $BUILD_DIR  --target sum_test
  sum:run:
    deps:
      - task: sum:test
    cmds:
      - $OUTPUT_DIR/$BUILD_TYPE/sum_test
